name: CI
on: [pull_request]
jobs:
  rspec:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.0.6', '3.1', '3.2']
    runs-on: ubuntu-latest
    env:
      DD_PROFILING_NO_EXTENSION: true
      RAILS_ENV: test
      RACK_ENV: test
      REDIS_URL: redis://localhost:6379/1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: synced-latency-data-collector-test
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: synced-latency-data-collector-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1

      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec
